apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mssqldb-controller
  name: mssqldb-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssqldb-controller
  template:
    metadata:
      labels:
        app: mssqldb-controller
    spec:
      containers:
      - image: mdrrakiburrahman/mssqldb-controller
        imagePullPolicy: Always
        name: mssqldb-controller
